version: 2.1
jobs:
  bobby:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
  sally:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Double trouble'
workflows:
  version: 2.1
  bobby_sally:
    - bobby
    - sally