version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: npm run build
  test:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: npm install
      - run: npm test
  hitme:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "i'm hit"
workflows:
  version: 2.1
  install_build_test:
    jobs:
      - build
      - hitme
      - test:
          requires:
            - hitme
